Ingredient.create(name: "ground beef")
Ingredient.create(name: "sirloin")
Ingredient.create(name: "ribeye steak")
Ingredient.create(name: "beef chuck")
Ingredient.create(name: "beef ribs")
Ingredient.create(name: "flank steak")
Ingredient.create(name: "porterhouse")
Ingredient.create(name: "round roast")
Ingredient.create(name: "filet mignon")
Ingredient.create(name: "NY strip steak")
Ingredient.create(name: "chicken breast")
Ingredient.create(name: "chicken thighs")
Ingredient.create(name: "chicken drumsticks")
Ingredient.create(name: "whole chicken")
Ingredient.create(name: "chicken wings")
Ingredient.create(name: "pork")
Ingredient.create(name: "pork chops")
Ingredient.create(name: "St. Louis style ribs")
Ingredient.create(name: "spare ribs")
Ingredient.create(name: "ground pork")
Ingredient.create(name: "country style pork ribs")
Ingredient.create(name: "bacon")
Ingredient.create(name: "pork sausage")
Ingredient.create(name: "Italina sausage")
Ingredient.create(name: "Andouille sausage")
Ingredient.create(name: "chorizo sausage")
Ingredient.create(name: "kielbasa")
Ingredient.create(name: "red onions")
Ingredient.create(name: "yellow onions")
Ingredient.create(name: "vidalia onions")
Ingredient.create(name: "white onions")
Ingredient.create(name: "green peppers")
Ingredient.create(name: "yellow peppers")
Ingredient.create(name: "red peppers")
Ingredient.create(name: "jalapeno peppers")
Ingredient.create(name: "chipotle peppers")
Ingredient.create(name: "garlic")
Ingredient.create(name: "celery")
Ingredient.create(name: "spinach")
Ingredient.create(name: "romaine lettuce")
Ingredient.create(name: "iceberg lettuce")
Ingredient.create(name: "spinach")
Ingredient.create(name: "kale")
Ingredient.create(name: "bok choy")
Ingredient.create(name: "arugala")
Ingredient.create(name: "cucumbers")
Ingredient.create(name: "Italian tomatoes")
Ingredient.create(name: "hot house tomatoes")
Ingredient.create(name: "cherry tomatoes")
Ingredient.create(name: "tomatoes")
Ingredient.create(name: "red potatoes")
Ingredient.create(name: "Idaho potatoes")
Ingredient.create(name: "Yukon Gold potatoes")
Ingredient.create(name: "white potatoes")
Ingredient.create(name: "Russet potatoes")
Ingredient.create(name: "sweet potatoes")
Ingredient.create(name: "avacados")
Ingredient.create(name: "yellow squash")
Ingredient.create(name: "green squash")
Ingredient.create(name: "carrots")
Ingredient.create(name: "beets")
Ingredient.create(name: "yams")
Ingredient.create(name: "zucchini")
Ingredient.create(name: "eggplant")
Ingredient.create(name: "thyme")
Ingredient.create(name: "oregano")
Ingredient.create(name: "parsely")
Ingredient.create(name: "sage")
Ingredient.create(name: "cumin")
Ingredient.create(name: "paprika")
Ingredient.create(name: "salt")
Ingredient.create(name: "pepper")
Ingredient.create(name: "marjoram")
Ingredient.create(name: "garlic powder")
Ingredient.create(name: "ground chili pepper")
Ingredient.create(name: "sugar")
Ingredient.create(name: "brown sugar")
Ingredient.create(name: "flour")
Ingredient.create(name: "baking powder")
Ingredient.create(name: "baking soda")
Ingredient.create(name: "vanilla extract")

User.create(name: "Bobby Flay", email: "bobby@mail.com", password: "badabing")
User.create(name: "Pasquali", email: "mritaly@mail.it", password: "alittlemorewine")
User.create(name: "Gina", email: "tiny@mail.com", password: "msitaly")
User.create(name: "Mario", email: "bigredcrocs@mail.com", password: "nodiet")
User.create(name: "Swedish Chef", email: "urgyburgyborkbork@mail.se", password: "Derlittlebirdy")
User.create(name: "Grandma", email: "cookies@mail.com", password: "all4mygrandkids")
User.create(name: "Keebler Elves", email: "elves@mail.tree", password: "magicsprinkles")
User.create(name: "Martha", email: "mrssnoop@mail.dogpound", password: "freedom")
User.create(name: "Remy Rat", email: "ratatouille@mail.fr", password: "bonappetit")
